version: 2
jobs:
  gcc_8_3_0:
    docker:
      - image: yumetodo/buildcontainers:gcc-8.3.0
    steps:
      - checkout
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=gcc .. && make run_test
          working_directory: build_gcc
  gcc_4_8_3:
    docker:
      - image: yumetodo/buildcontainers:gcc-4.8.3
    steps:
      - checkout
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=gcc .. && make run_test
          working_directory: build_gcc
  clang_5_0_2:
    docker:
      - image: yumetodo/buildcontainers:clang-5.0.2
    steps:
      - checkout
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=clang .. && make run_test
          working_directory: build_clang
  clang_3_4_1:
    docker:
      - image: yumetodo/buildcontainers:clang-3.4.1
    steps:
      - checkout
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=clang .. && make run_test
          working_directory: build_clang
workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_8_3_0
      - gcc_4_8_3
      - clang_5_0_2
      - clang_3_4_1
