version: 2
jobs:
  gcc_8_2:
    docker:
      - image: enumack/buildcontainers:gcc-8.2
    steps:
      - checkout
      - run: ls -l
      - run:
          command: pwd && ls -l
      - run:
          command: pwd && ls -l
          working_directory: build_gcc
      - run:
          name: git submodule
          command: git submodule update --init
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX .. && make run_test
          working_directory: build_gcc
  gcc_4_8:
    docker:
      - image: enumack/buildcontainers:gcc-4.8
    steps:
      - checkout
      - run: ls -l
      - run:
          command: pwd && ls -l
      - run:
          command: pwd && ls -l
          working_directory: build_gcc
      - run:
          name: git submodule
          command: git submodule update --init
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX .. && make run_test
          working_directory: build_gcc
  clang_7_0_0:
    docker:
      - image: enumack/buildcontainers:clang-7.0.0
    steps:
      - checkout
      - run: ls -l
      - run:
          command: pwd && ls -l
      - run:
          command: pwd && ls -l
          working_directory: build_gcc
      - run:
          name: git submodule
          command: git submodule update --init
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX .. && make run_test
          working_directory: build_clang
  clang_3_4:
    docker:
      - image: enumack/buildcontainers:clang-3.4
    steps:
      - checkout
      - run: ls -l
      - run:
          command: pwd && ls -l
      - run:
          command: pwd && ls -l
          working_directory: build_gcc
      - run:
          name: git submodule
          command: git submodule update --init
      - run:
          name: build
          command: cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX .. && make run_test
          working_directory: build_clang
workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc_8_2
      - gcc_4_8
      - clang_7_0_0
      - clang_3_4
